import {
  StaffUser,
  ProductItem,
  CashShift,
  StockAlert,
  PurchaseOrder,
  Invoice,
} from '@/types/pos';

export const INITIAL_STAFF: StaffUser[] = [
  {
    id: 'emp-1',
    nombre: 'Elizabeth Reyes',
    cedula: '001-140590-0001A',
    cargo: 'Administradora',
    sucursal: 'Todas',
    jefeDirecto: '—',
    grupo: 'Administrador',
    estado: 'Activo',
    role: 'admin',
    avatar: 'ER',
    telefono: '+505 8811-2200',
    correo: 'elizabeth.reyes@construye.com.ni',
    fechaIngreso: '10/01/2023',
    usuario: 'elizabeth.reyes',
    salarioBase: 28000.0,
    bonosVigentes: 3500.0,
  },
  {
    id: 'emp-2',
    nombre: 'Carlos Vado',
    cedula: '001-220488-0004B',
    cargo: 'Bodeguero',
    sucursal: 'Managua Centro',
    jefeDirecto: 'Elizabeth Reyes',
    grupo: 'Bodeguero',
    estado: 'Activo',
    role: 'bodeguero',
    avatar: 'CV',
    telefono: '+505 8811-2233',
    correo: 'cvado@construye.com.ni',
    fechaIngreso: '03/02/2024',
    usuario: 'carlos.vado',
    salarioBase: 14500.0,
    bonosVigentes: 1200.0,
  },
  {
    id: 'emp-3',
    nombre: 'María Alemán',
    cedula: '001-090195-0009C',
    cargo: 'Cajera',
    sucursal: 'Managua Centro',
    jefeDirecto: 'Elizabeth Reyes',
    grupo: 'Cajero',
    estado: 'Activo',
    role: 'cajero',
    avatar: 'MA',
    telefono: '+505 8811-2255',
    correo: 'maleman@construye.com.ni',
    fechaIngreso: '15/06/2024',
    usuario: 'maria.aleman',
    salarioBase: 13000.0,
    bonosVigentes: 800.0,
  },
  {
    id: 'emp-4',
    nombre: 'José Baltodano',
    cedula: '001-051292-0021D',
    cargo: 'Cajero / Bodeguero',
    sucursal: 'Ciudad Sandino',
    jefeDirecto: 'Elizabeth Reyes',
    grupo: 'Cajero',
    estado: 'Activo',
    role: 'cajero',
    avatar: 'JB',
    telefono: '+505 8811-2277',
    correo: 'jbaltodano@construye.com.ni',
    fechaIngreso: '20/08/2024',
    usuario: 'jose.baltodano',
    salarioBase: 13500.0,
    bonosVigentes: 500.0,
  },
  {
    id: 'emp-5',
    nombre: 'Ricardo Palacios',
    cedula: '001-170687-0033E',
    cargo: 'Cajero (baja)',
    sucursal: 'Sabana Grande',
    jefeDirecto: 'Elizabeth Reyes',
    grupo: 'Sin grupo',
    estado: 'Inactivo',
    role: 'cajero',
    avatar: 'RP',
    telefono: '+505 8811-2299',
    correo: 'rpalacios@construye.com.ni',
    fechaIngreso: '01/11/2023',
    usuario: 'ricardo.palacios',
    salarioBase: 0.0,
    bonosVigentes: 0.0,
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: 1,
    codigo: 'FER-01523',
    nombre: 'Taladro Percutor DeWalt DCD771 20V',
    marca: 'DeWalt',
    categoria: 'Herramientas eléctricas',
    categoriaSlug: 'herramientas-electricas',
    unidad: 'Unidad',
    precioSinIva: 3450.0,
    ivaPorcentaje: 15,
    precioConIva: 3967.5,
    costoUnitario: 2180.0,
    stock: 6.0,
    disponible: 5.0,
    comprometido: 1.0,
    estado: 'Activo',
    descripcion: 'Motor sin carbones, incluye batería 20V MAX y cargador de alta velocidad.',
    proveedorHabitual: 'DeWalt Centroamérica',
    puntoReorden: 5.0,
    publicadoWeb: true,
    codigoFiscal: '8467.21.00',
    sucursalesStock: [
      { sucursal: 'Managua Centro', stock: 6.0, comprometido: 1.0, disponible: 5.0 },
      { sucursal: 'Ciudad Sandino', stock: 3.0, comprometido: 0.0, disponible: 3.0 },
      { sucursal: 'Sabana Grande', stock: 0.0, comprometido: 0.0, disponible: 0.0 },
    ],
    historialPrecios: [
      {
        vigenteDesde: '15 sep 2026, 09:12',
        hasta: '—',
        costoProm: 2180.0,
        precioSinIva: 3450.0,
        precioConIva: 3967.5,
      },
      {
        vigenteDesde: '02 jul 2026, 14:30',
        hasta: '15 sep 2026, 09:12',
        costoProm: 2050.0,
        precioSinIva: 3450.0,
        precioConIva: 3967.5,
      },
      {
        vigenteDesde: '11 mar 2026, 10:05',
        hasta: '02 jul 2026, 14:30',
        costoProm: 1990.0,
        precioSinIva: 3300.0,
        precioConIva: 3795.0,
      },
    ],
    kardex: [
      {
        fecha: '24 sep, 09:04',
        tipo: 'Venta',
        cantidad: -1.0,
        documento: 'Factura 000345',
        empleado: 'María Alemán',
        referencia: 'Ticket POS-345',
      },
      {
        fecha: '20 sep, 16:40',
        tipo: 'Reserva',
        cantidad: -1.0,
        documento: 'Pedido 01188',
        empleado: 'Tienda web',
        referencia: 'Pedido CW-001188',
      },
      {
        fecha: '15 sep, 09:12',
        tipo: 'Entrada',
        cantidad: 8.0,
        documento: 'Compra 000108',
        empleado: 'Carlos Vado',
        referencia: 'OC-000108',
      },
      {
        fecha: '02 sep, 11:20',
        tipo: 'Venta',
        cantidad: -1.0,
        documento: 'Factura 000298',
        empleado: 'María Alemán',
        referencia: 'Ticket POS-298',
      },
      {
        fecha: '30 ago, 08:15',
        tipo: 'Ajuste',
        cantidad: -1.0,
        documento: '—',
        empleado: 'Elizabeth Reyes',
        referencia: 'Conteo físico · unidad dañada',
      },
    ],
  },
  {
    id: 2,
    codigo: 'FER-00981',
    nombre: 'Martillo Stanley 16oz Fibra',
    marca: 'Stanley',
    categoria: 'Herramientas manuales',
    categoriaSlug: 'herramientas-manuales',
    unidad: 'Unidad',
    precioSinIva: 247.83,
    ivaPorcentaje: 15,
    precioConIva: 285.0,
    costoUnitario: 178.2,
    stock: 42.0,
    disponible: 40.0,
    comprometido: 2.0,
    estado: 'Activo',
    descripcion: 'Mango de fibra de vidrio ergonómico, cabeza de acero forjado.',
    proveedorHabitual: 'Distribuidora Truper Nicaragua',
    puntoReorden: 10.0,
    publicadoWeb: true,
    codigoFiscal: '8205.20.00',
    sucursalesStock: [
      { sucursal: 'Managua Centro', stock: 42.0, comprometido: 2.0, disponible: 40.0 },
      { sucursal: 'Ciudad Sandino', stock: 15.0, comprometido: 0.0, disponible: 15.0 },
      { sucursal: 'Sabana Grande', stock: 8.0, comprometido: 0.0, disponible: 8.0 },
    ],
  },
  {
    id: 3,
    codigo: 'FER-04410',
    nombre: 'Tornillo Hex 1/4x2" (caja 100)',
    marca: 'Truper',
    categoria: 'Tornillería y Fijación',
    categoriaSlug: 'tornilleria',
    unidad: 'Caja',
    precioSinIva: 165.22,
    ivaPorcentaje: 15,
    precioConIva: 190.0,
    costoUnitario: 140.0,
    stock: 2.0,
    disponible: 2.0,
    comprometido: 0.0,
    estado: 'Activo',
    descripcion: 'Tornillo hexagonal grado 5 con acabado galvanizado.',
    proveedorHabitual: 'Distribuidora Truper Nicaragua',
    puntoReorden: 5.0,
    publicadoWeb: true,
    codigoFiscal: '7318.15.00',
    sucursalesStock: [
      { sucursal: 'Ciudad Sandino', stock: 2.0, comprometido: 0.0, disponible: 2.0 },
      { sucursal: 'Managua Centro', stock: 12.0, comprometido: 0.0, disponible: 12.0 },
    ],
  },
  {
    id: 4,
    codigo: 'FER-02207',
    nombre: 'Disco Corte Bosch 4.5"',
    marca: 'Bosch',
    categoria: 'Herramientas eléctricas',
    categoriaSlug: 'herramientas-electricas',
    unidad: 'Unidad',
    precioSinIva: 56.52,
    ivaPorcentaje: 15,
    precioConIva: 65.0,
    costoUnitario: 42.0,
    stock: 6.0,
    disponible: 6.0,
    comprometido: 0.0,
    estado: 'Activo',
    descripcion: 'Disco abrasivo para corte de metal y acero inoxidable estándar.',
    proveedorHabitual: 'Ferretería Mayoreo Bosch',
    puntoReorden: 8.0,
    publicadoWeb: true,
    codigoFiscal: '6804.22.00',
    sucursalesStock: [
      { sucursal: 'Managua Centro', stock: 6.0, comprometido: 0.0, disponible: 6.0 },
      { sucursal: 'Ciudad Sandino', stock: 10.0, comprometido: 0.0, disponible: 10.0 },
    ],
  },
  {
    id: 5,
    codigo: 'FER-03390',
    nombre: 'Cable THHN Cal. 12 (metro)',
    marca: 'Centelsa',
    categoria: 'Eléctrico',
    categoriaSlug: 'electrico',
    unidad: 'Metro',
    esFraccionable: true,
    precioSinIva: 16.09,
    ivaPorcentaje: 15,
    precioConIva: 18.5,
    costoUnitario: 11.5,
    stock: 18.0,
    disponible: 18.0,
    comprometido: 0.0,
    estado: 'Activo',
    descripcion: 'Cable de cobre unipolar termoplástico resistente al calor y humedad.',
    proveedorHabitual: 'Centelsa Nicaragua',
    puntoReorden: 20.0,
    publicadoWeb: true,
    codigoFiscal: '8544.49.00',
    sucursalesStock: [
      { sucursal: 'Managua Centro', stock: 18.0, comprometido: 0.0, disponible: 18.0 },
      { sucursal: 'Ciudad Sandino', stock: 50.0, comprometido: 0.0, disponible: 50.0 },
    ],
  },
  {
    id: 6,
    codigo: 'FER-00760',
    nombre: 'Cemento Canal Holcim 42.5kg',
    marca: 'Holcim',
    categoria: 'Construcción',
    categoriaSlug: 'construccion',
    unidad: 'Bolsa',
    precioSinIva: 323.48,
    ivaPorcentaje: 15,
    precioConIva: 372.0,
    costoUnitario: 290.0,
    stock: 4.0,
    disponible: 4.0,
    comprometido: 0.0,
    estado: 'Activo',
    descripcion: 'Cemento hidráulico de uso general para mampostería y estructuras.',
    proveedorHabitual: 'Holcim Nicaragua S.A.',
    puntoReorden: 10.0,
    publicadoWeb: false,
    codigoFiscal: '2523.29.00',
    sucursalesStock: [
      { sucursal: 'Managua Centro', stock: 4.0, comprometido: 0.0, disponible: 4.0 },
      { sucursal: 'Sabana Grande', stock: 30.0, comprometido: 0.0, disponible: 30.0 },
    ],
  },
  {
    id: 7,
    codigo: 'FER-09112',
    nombre: 'Serrucho Truper 20"',
    marca: 'Truper',
    categoria: 'Herramientas manuales',
    categoriaSlug: 'herramientas-manuales',
    unidad: 'Unidad',
    precioSinIva: 170.0,
    ivaPorcentaje: 15,
    precioConIva: 195.5,
    costoUnitario: 125.0,
    stock: 1.0,
    disponible: 1.0,
    comprometido: 0.0,
    estado: 'Descontinuado',
    descripcion: 'Hoja de acero SK5 con dientes de triple filo templados.',
    proveedorHabitual: 'Distribuidora Truper Nicaragua',
    puntoReorden: 3.0,
    publicadoWeb: false,
    codigoFiscal: '8202.10.00',
    sucursalesStock: [
      { sucursal: 'Managua Centro', stock: 1.0, comprometido: 0.0, disponible: 1.0 },
    ],
  },
  {
    id: 8,
    codigo: 'FER-05561',
    nombre: 'Pintura Sherwin Williams Blanco Gl.',
    marca: 'Sherwin Williams',
    categoria: 'Pintura',
    categoriaSlug: 'pintura',
    unidad: 'Galón',
    precioSinIva: 852.17,
    ivaPorcentaje: 15,
    precioConIva: 980.0,
    costoUnitario: 650.0,
    stock: 3.0,
    disponible: 3.0,
    comprometido: 0.0,
    estado: 'Activo',
    descripcion: 'Pintura látex acrílica lavable para interiores y exteriores.',
    proveedorHabitual: 'Sherwin Williams NIC',
    puntoReorden: 5.0,
    publicadoWeb: true,
    codigoFiscal: '3209.10.00',
    sucursalesStock: [
      { sucursal: 'Sabana Grande', stock: 3.0, comprometido: 0.0, disponible: 3.0 },
      { sucursal: 'Managua Centro', stock: 14.0, comprometido: 0.0, disponible: 14.0 },
    ],
  },
];

export const INITIAL_SHIFTS: CashShift[] = [
  {
    id: 'shift-1',
    turnoNumero: '#00214',
    caja: 'Caja 1 · Managua Centro',
    sucursal: 'Managua Centro',
    cajero: 'María Alemán',
    cajeroAvatar: 'MA',
    fecha: '24/09/2026',
    horaApertura: '07:58 a.m.',
    estado: 'Faltante',
    fondoInicial: 2000.0,
    ventasEfectivo: 8170.0,
    devoluciones: 570.0,
    ingresosManuales: 500.0,
    egresosManuales: 120.0,
    efectivoEsperado: 9980.0,
    efectivoContado: 9937.5,
    diferencia: -42.5,
    observaciones: 'Posible error de vuelto en venta FAC-000345, se revisará con el cliente.',
    movimientos: [
      { id: 'm-1', hora: '08:12', tipo: 'Venta', referencia: 'FAC-000341', monto: 3000.0 },
      { id: 'm-2', hora: '09:04', tipo: 'Venta', referencia: 'FAC-000345', monto: 850.0 },
      { id: 'm-3', hora: '10:30', tipo: 'Devolución', referencia: 'FAC-000341 (anulada)', monto: -570.0 },
      { id: 'm-4', hora: '11:15', tipo: 'Ingreso manual', referencia: 'Cambio de billetes desde Caja 2', monto: 500.0 },
      { id: 'm-5', hora: '13:40', tipo: 'Egreso manual', referencia: 'Compra de bolsas para empaque', monto: -120.0 },
      { id: 'm-6', hora: '15:02', tipo: 'Venta', referencia: 'FAC-000358', monto: 4320.0 },
    ],
  },
  {
    id: 'shift-2',
    turnoNumero: '#00215',
    caja: 'Caja 2 · Managua Centro',
    sucursal: 'Managua Centro',
    cajero: 'Carlos Vado',
    cajeroAvatar: 'CV',
    fecha: '24/09/2026',
    horaApertura: '08:03 a.m.',
    estado: 'Abierta',
    fondoInicial: 2000.0,
    ventasEfectivo: 6540.0,
    devoluciones: 0.0,
    ingresosManuales: 0.0,
    egresosManuales: 0.0,
    efectivoEsperado: 8540.0,
    movimientos: [],
  },
  {
    id: 'shift-3',
    turnoNumero: '#00216',
    caja: 'Caja Mostrador · Ciudad Sandino',
    sucursal: 'Ciudad Sandino',
    cajero: 'José Baltodano',
    cajeroAvatar: 'JB',
    fecha: '24/09/2026',
    horaApertura: '08:00 a.m.',
    estado: 'Cerca del tope',
    fondoInicial: 2000.0,
    ventasEfectivo: 17300.0,
    devoluciones: 0.0,
    ingresosManuales: 0.0,
    egresosManuales: 0.0,
    efectivoEsperado: 19300.0,
    topeMaximo: 20000.0,
    movimientos: [],
  },
  {
    id: 'shift-4',
    turnoNumero: '#00213',
    caja: 'Caja 1 · Sabana Grande',
    sucursal: 'Sabana Grande',
    cajero: 'Ricardo Palacios',
    cajeroAvatar: 'RP',
    fecha: '24/09/2026',
    horaApertura: '07:30 a.m.',
    horaCierre: '12:40 p.m.',
    estado: 'Faltante',
    fondoInicial: 1500.0,
    ventasEfectivo: 3316.0,
    devoluciones: 0.0,
    ingresosManuales: 0.0,
    egresosManuales: 0.0,
    efectivoEsperado: 4816.0,
    efectivoContado: 4773.5,
    diferencia: -42.5,
    movimientos: [],
  },
];

export const INITIAL_STOCK_ALERTS: StockAlert[] = [
  {
    id: 'alt-1',
    producto: 'Tornillo Hex 1/4 x 2" (caja 100)',
    codigo: 'FER-04410',
    sucursal: 'Ciudad Sandino',
    stock: 2.0,
    disponible: 2.0,
    umbral: 5.0,
    faltante: 3.0,
    proveedorSugerido: 'Truper Nicaragua',
    nivel: 'Crítico',
    accion: 'Agregar a OC',
  },
  {
    id: 'alt-2',
    producto: 'Cemento Canal Holcim 42.5kg',
    codigo: 'FER-00760',
    sucursal: 'Managua Centro',
    stock: 4.0,
    disponible: 4.0,
    umbral: 10.0,
    faltante: 6.0,
    proveedorSugerido: 'Holcim Nicaragua S.A.',
    nivel: 'Crítico',
    accion: 'Agregar a OC',
  },
  {
    id: 'alt-3',
    producto: 'Disco de Corte Bosch 4.5"',
    codigo: 'FER-02207',
    sucursal: 'Managua Centro',
    stock: 6.0,
    disponible: 6.0,
    umbral: 8.0,
    faltante: 2.0,
    proveedorSugerido: 'Ferretería Mayoreo Bosch',
    nivel: 'Bajo',
    accion: 'Agregar a OC',
  },
  {
    id: 'alt-4',
    producto: 'Cable THHN Calibre 12 (m)',
    codigo: 'FER-03390',
    sucursal: 'Managua Centro',
    stock: 18.0,
    disponible: 18.0,
    umbral: 20.0,
    faltante: 2.0,
    proveedorSugerido: 'Centelsa Nicaragua',
    nivel: 'Bajo',
    accion: 'Agregar a OC',
  },
  {
    id: 'alt-5',
    producto: 'Pintura Sherwin Williams Blanco Gl.',
    codigo: 'FER-05561',
    sucursal: 'Sabana Grande',
    stock: 3.0,
    disponible: 3.0,
    umbral: 5.0,
    faltante: 2.0,
    proveedorSugerido: 'Sherwin Williams NIC',
    nivel: 'Bajo',
    accion: 'Agregar a OC',
  },
  {
    id: 'alt-6',
    producto: 'Taladro DeWalt DCD771 20V',
    codigo: 'FER-01523',
    sucursal: 'Managua Centro',
    stock: 6.0,
    disponible: 5.0,
    umbral: 5.0,
    faltante: 0.0,
    proveedorSugerido: 'DeWalt Centroamérica',
    nivel: 'Bajo',
    accion: 'Sin acción',
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    folio: 'OC-000112',
    proveedor: 'Distribuidora Truper Nicaragua',
    sucursalDestino: 'Managua Centro',
    fecha: '24/09/2026',
    registradaPor: 'Carlos Vado',
    total: 73830.0,
    subtotal: 64200.0,
    iva: 9630.0,
    unidades: 2280,
    estado: 'Pendiente',
    documentoProveedor: 'FACT-TRP-55210',
    lineas: [
      {
        producto: 'Martillo Stanley 16oz Fibra',
        codigo: 'FER-00981',
        cantidad: 60.0,
        costoUnitario: 185.0,
        ivaPorc: 15.0,
        subtotal: 11100.0,
      },
      {
        producto: 'Tornillo Hex 1/4 x 2" (caja 100)',
        codigo: 'FER-04410',
        cantidad: 120.0,
        costoUnitario: 165.0,
        ivaPorc: 15.0,
        subtotal: 19800.0,
      },
      {
        producto: 'Disco de Corte Bosch 4.5"',
        codigo: 'FER-02207',
        cantidad: 300.0,
        costoUnitario: 42.0,
        ivaPorc: 15.0,
        subtotal: 12600.0,
      },
      {
        producto: 'Cable THHN Calibre 12 (metro)',
        codigo: 'FER-03390',
        cantidad: 1800.0,
        costoUnitario: 11.5,
        ivaPorc: 15.0,
        subtotal: 20700.0,
      },
    ],
  },
  {
    folio: 'OC-000111',
    proveedor: 'Holcim Nicaragua S.A.',
    sucursalDestino: 'Managua Centro',
    fecha: '22/09/2026',
    registradaPor: 'Carlos Vado',
    total: 156400.0,
    subtotal: 136000.0,
    iva: 20400.0,
    unidades: 400,
    estado: 'Pendiente',
    documentoProveedor: 'HOLCIM-FACT-9821',
    lineas: [
      {
        producto: 'Cemento Canal Holcim 42.5kg',
        codigo: 'FER-00760',
        cantidad: 400.0,
        costoUnitario: 340.0,
        ivaPorc: 15.0,
        subtotal: 136000.0,
      },
    ],
  },
  {
    folio: 'OC-000110',
    proveedor: 'Ferretería Mayoreo Bosch',
    sucursalDestino: 'Ciudad Sandino',
    fecha: '18/09/2026',
    registradaPor: 'José Baltodano',
    total: 31050.0,
    subtotal: 27000.0,
    iva: 4050.0,
    unidades: 600,
    estado: 'Recibida',
    documentoProveedor: 'BOSCH-MAY-4401',
    lineas: [
      {
        producto: 'Disco de Corte Bosch 4.5"',
        codigo: 'FER-02207',
        cantidad: 600.0,
        costoUnitario: 45.0,
        ivaPorc: 15.0,
        subtotal: 27000.0,
      },
    ],
  },
  {
    folio: 'OC-000109',
    proveedor: 'DeWalt Centroamérica',
    sucursalDestino: 'Sabana Grande',
    fecha: '14/09/2026',
    registradaPor: 'Carlos Vado',
    total: 62880.0,
    subtotal: 54678.26,
    iva: 8201.74,
    unidades: 25,
    estado: 'Anulada',
    documentoProveedor: 'DW-CAN-0091',
    lineas: [
      {
        producto: 'Taladro Percutor DeWalt DCD771 20V',
        codigo: 'FER-01523',
        cantidad: 25.0,
        costoUnitario: 2187.13,
        ivaPorc: 15.0,
        subtotal: 54678.26,
      },
    ],
  },
  {
    folio: 'OC-000108',
    proveedor: 'DeWalt Centroamérica',
    sucursalDestino: 'Managua Centro',
    fecha: '15/09/2026',
    registradaPor: 'Carlos Vado',
    total: 17440.0,
    subtotal: 15165.22,
    iva: 2274.78,
    unidades: 8,
    estado: 'Recibida',
    documentoProveedor: 'DW-REC-8891',
    lineas: [
      {
        producto: 'Taladro Percutor DeWalt DCD771 20V',
        codigo: 'FER-01523',
        cantidad: 8.0,
        costoUnitario: 1895.65,
        ivaPorc: 15.0,
        subtotal: 15165.22,
      },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    numero: 'FAC-000358',
    fecha: '24/09/2026',
    hora: '15:02',
    canal: 'POS',
    cliente: 'Consumidor Final',
    sucursal: 'Managua Centro',
    cajero: 'María Alemán',
    caja: 'Caja 1',
    total: 4952.76,
    subtotal: 4306.75,
    iva: 646.01,
    descuento: 0.0,
    estado: 'Emitida',
    sesionCaja: '#00214',
    utilidadEstimada: 1592.1,
    pagos: [
      { id: 'p-1', metodo: 'Efectivo', monto: 3000.0 },
      { id: 'p-2', metodo: 'Tarjeta', monto: 1952.76, referencia: 'POS-VISA-99231' },
    ],
    lineas: [
      {
        producto: 'Martillo Stanley 16oz',
        codigo: 'FER-00981',
        cantidad: 2.0,
        precioUnit: 285.0,
        desc: 0.0,
        ivaPorc: 15.0,
        subtotal: 570.0,
        costoUnit: 178.2,
      },
      {
        producto: 'Taladro DeWalt DCD771',
        codigo: 'FER-01523',
        cantidad: 1.0,
        precioUnit: 3450.0,
        desc: 0.0,
        ivaPorc: 15.0,
        subtotal: 3450.0,
        costoUnit: 2180.0,
      },
      {
        producto: 'Cable THHN Cal. 12',
        codigo: 'FER-03390',
        cantidad: 15.5,
        precioUnit: 18.5,
        desc: 0.0,
        ivaPorc: 15.0,
        subtotal: 286.75,
        costoUnit: 11.5,
      },
    ],
  },
  {
    numero: 'FAC-000357',
    fecha: '24/09/2026',
    hora: '14:20',
    canal: 'E-commerce',
    cliente: 'Constructora Vega y Asoc.',
    clienteRuc: 'J0310000456789',
    sucursal: 'Bodega e-commerce',
    cajero: 'Pedido CW-001190',
    caja: 'E-commerce Online',
    total: 12840.5,
    subtotal: 11165.65,
    iva: 1674.85,
    descuento: 0.0,
    estado: 'Emitida',
    utilidadEstimada: 4210.0,
    pagos: [{ id: 'p-3', metodo: 'Tarjeta', monto: 12840.5, referencia: 'STRIPE-CH-9982' }],
    lineas: [
      {
        producto: 'Cemento Canal Holcim 42.5kg',
        codigo: 'FER-00760',
        cantidad: 30.0,
        precioUnit: 372.0,
        desc: 0.0,
        ivaPorc: 15.0,
        subtotal: 11160.0,
        costoUnit: 290.0,
      },
    ],
  },
  {
    numero: 'FAC-000346',
    fecha: '24/09/2026',
    hora: '12:10',
    canal: 'POS',
    cliente: 'Ferretería El Tanque (RUC J0310000123456)',
    clienteRuc: 'J0310000123456',
    sucursal: 'Managua Centro',
    cajero: 'Carlos Vado',
    caja: 'Caja 2',
    total: 8970.0,
    subtotal: 7800.0,
    iva: 1170.0,
    descuento: 0.0,
    estado: 'Emitida',
    utilidadEstimada: 2850.0,
    pagos: [{ id: 'p-4', metodo: 'Transferencia', monto: 8970.0, referencia: 'BAC-TRF-88192' }],
    lineas: [],
  },
  {
    numero: 'FAC-000345',
    fecha: '24/09/2026',
    hora: '09:04',
    canal: 'POS',
    cliente: 'Consumidor Final',
    sucursal: 'Managua Centro',
    cajero: 'María Alemán',
    caja: 'Caja 1',
    total: 850.0,
    subtotal: 739.13,
    iva: 110.87,
    descuento: 0.0,
    estado: 'Emitida',
    utilidadEstimada: 290.0,
    pagos: [{ id: 'p-5', metodo: 'Efectivo', monto: 850.0 }],
    lineas: [],
  },
  {
    numero: 'FAC-000341',
    fecha: '24/09/2026',
    hora: '08:12',
    canal: 'POS',
    cliente: 'Consumidor Final',
    sucursal: 'Managua Centro',
    cajero: 'María Alemán',
    caja: 'Caja 1',
    total: 570.0,
    subtotal: 495.65,
    iva: 74.35,
    descuento: 0.0,
    estado: 'Anulada',
    pagos: [{ id: 'p-6', metodo: 'Efectivo', monto: 570.0 }],
    lineas: [],
  },
];
